### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by waupdog** [CyberPunkMetalHead/binance-dca-crypto-trading-bot#1]
When running in live mode: 

Traceback (most recent call last):
  File "/home/pi/crypto/binance-dca-crypto-trading-bot/main.py", line 97, in <module>
    main()
  File "/home/pi/crypto/binance-dca-crypto-trading-bot/main.py", line 41, in main
    log.warning("RUNNING IN LIVE MODE! PAUSING FOR 1 MINUTE")
NameError: name 'log' is not defined

changing log.warning to logging.warning in main.py resolves the problem

**Comment by CyberPunkMetalHead** [comment]
Thank you!
